package rjoerod.savemywalk.route;

import com.google.android.gms.maps.model.LatLng;
import java.util.ArrayList;

/**
 * Created by Ryan on 6/15/2017.
 */

public class RouteData {

    private String routeID;     // rt# where # is generated by UTC
    private String routeName;   // name given by the user
    private ArrayList<LatLng> coordinates = new ArrayList<LatLng>(); // each point in the route, first to last

    // Constructor: Sets up route ID and route name
    public RouteData(String someRouteID, String someRouteName) {
        routeID = someRouteID;
        routeName = someRouteName;
    }

    // Add a coordinate to the end of the list
    public void addCoordinate(Double lat, Double lng) {
        LatLng newCoordinate = new LatLng(lat, lng);
        coordinates.add(newCoordinate);
    }

    // Return route id
    public String getRouteID() {
        return routeID;
    }

    // Return route name
    public String getRouteName() {
        return routeName;
    }

    // Return coordinates from a certain row
    // Index is valid for 0 -> (length-1)
    public LatLng getCoordinate(int index) {
        return coordinates.get(index);
    }

    // Return array
    public ArrayList<LatLng> getAllCoords() {
        return coordinates;
    }

    // Return length of outer array
    public int getLength() {
        return coordinates.size();
    }

    // Remove all coordinates
    public void clear() {
        coordinates.clear();
    }
}
